Controllers/PessoaFilmesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Watch_List.Data;
using Watch_List.Models;

namespace Watch_List.Controllers
{
    
    [Authorize]
    public class PessoaFilmesController : Controller
    {
        private readonly WatchListDbContext _context;

        public PessoaFilmesController(WatchListDbContext context)
        {
            _context = context;
        }

        // GET: PessoaFilmes
        public async Task<IActionResult> Index()
        {
            var watchListDbContext = _context.PessoaFilme.Include(p => p.Filme).Include(p => p.Pessoa);
            return View(await watchListDbContext.ToListAsync());
        }

        // GET: PessoaFilmes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoaFilme = await _context.PessoaFilme
                .Include(p => p.Filme)
                .Include(p => p.Pessoa)
                
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pessoaFilme == null)
            {
                return NotFound();
            }

            return View(pessoaFilme);
        }

        // GET: PessoaFilmes/Create
        public IActionResult Create()
        {
            ViewData["FilmeFK"] = new SelectList(_context.Filme, "Id", "Titulo");
            ViewData["PessoaFK"] = new SelectList(_context.Pessoa, "Id", "Nome");
            return View();
        }

        // POST: PessoaFilmes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Premio,FilmeFK,PessoaFK")] PessoaFilme pessoaFilme)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pessoaFilme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FilmeFK"] = new SelectList(_context.Filme, "Id", "Titulo", pessoaFilme.FilmeFK);
            ViewData["PessoaFK"] = new SelectList(_context.Pessoa, "Id", "Nome", pessoaFilme.PessoaFK);
            return RedirectToAction("Index","Filmes");
        }

        // GET: PessoaFilmes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoaFilme = await _context.PessoaFilme.FindAsync(id);
            if (pessoaFilme == null)
            {
                return NotFound();
            }
            ViewData["FilmeFK"] = new SelectList(_context.Filme, "Id", "Titulo", pessoaFilme.FilmeFK);
            ViewData["PessoaFK"] = new SelectList(_context.Pessoa, "Id", "Nome", pessoaFilme.PessoaFK);
            return View(pessoaFilme);
        }

        // POST: PessoaFilmes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Premio,FilmeFK,PessoaFK")] PessoaFilme pessoaFilme)
        {
            if (id != pessoaFilme.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pessoaFilme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PessoaFilmeExists(pessoaFilme.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FilmeFK"] = new SelectList(_context.Filme, "Id", "Titulo", pessoaFilme.FilmeFK);
            ViewData["PessoaFK"] = new SelectList(_context.Pessoa, "Id", "Nome", pessoaFilme.PessoaFK);
            return View(pessoaFilme);
        }

        // GET: PessoaFilmes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoaFilme = await _context.PessoaFilme
                .Include(p => p.Filme)
                .Include(p => p.Pessoa)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pessoaFilme == null)
            {
                return NotFound();
            }

            return View(pessoaFilme);
        }

        // POST: PessoaFilmes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pessoaFilme = await _context.PessoaFilme.FindAsync(id);
            _context.PessoaFilme.Remove(pessoaFilme);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PessoaFilmeExists(int id)
        {
            return _context.PessoaFilme.Any(e => e.Id == id);
        }
    }
}

Controllers/PessoasController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Watch_List.Data;
using Watch_List.Models;

namespace Watch_List.Controllers
{
   // [Authorize]
    public class PessoasController : Controller
    {
        /// <summary>
        /// Representa a bd
        /// </summary>
        private readonly WatchListDbContext _context;

        /// <summary>
        /// Atributo de dados da app web 
        /// </summary>
        private readonly IWebHostEnvironment _caminho;

     

        public PessoasController(WatchListDbContext context, IWebHostEnvironment caminho)
        {
            _context = context;
            _caminho = caminho;

        }

        [AllowAnonymous]
        /// <summary>
        /// Mostra a lista de pessoas 
        /// </summary>
        /// <returns></returns>
        // GET: Pessoas
        public async Task<IActionResult> Index()
        {

            //Profissões associadas a pessoas
           // var profissoes = await _context.Pessoa.Include(f => f.Profissoes).ToListAsync();

            return View(await _context.Pessoa.ToListAsync());
        }

        /// <summary>
        /// Mostra os detalhes de uma pessoa
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Pessoas/Details/5
      
        public async Task<IActionResult> Details(int? id)
        {
            //se não houver id
            if (id == null)
            {
                return RedirectToAction("Index");
            }


            var pessoa = await _context.Pessoa
                .Include(p => p.Profissoes)
                .FirstOrDefaultAsync(p => p.Id == id);

            ViewData["ListaDeFilmes"] = await (from p in _context.Pessoa
                                                join pf in _context.PessoaFilme on p.Id equals pf.PessoaFK
                                                join f in _context.Filme on pf.FilmeFK equals f.Id
                                               where p.Id == id
                                                select f).ToListAsync();

           


            //se nao houver pessoas
            if (pessoa == null)
            {
                return RedirectToAction("Index");
            }

            return View(pessoa);
        }

        /// <summary>
        /// Mostra a página de criação e pessoa
        /// </summary>
        /// <returns></returns>
        // GET: Pessoas/Create
        [Authorize(Roles = "Funcionario,Gestor")]
        public IActionResult Create()
        {
            var profissao = (from pr in _context.Profissao
                           join p in _context.Pessoa on pr.Id equals p.ProfissaoFK
                             select pr)
                 .OrderBy(pr => pr.Tarefa);

            ViewData["ProFK"] = new SelectList(profissao, "Id", "Tarefa");
            return View();
        }

        // POST: Pessoas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Funcionario,Gestor")]
        public async Task<IActionResult> Create([Bind("Id,Nome,Foto,DataNasc,DataObi,DataInic,Nacionalidade,ProfissaoFK")] Pessoa pessoa, IFormFile imagem)
        {
            if (pessoa.ProfissaoFK < 0)
            {
                // não foi escolhido uma profissao válida 
                ModelState.AddModelError("", "Não se esqueça de escolher uma profissão...");
                // devolver o controlo à View
                var profissao = (from pr in _context.Profissao
                                 join p in _context.Pessoa on pr.Id equals p.ProfissaoFK
                                 select pr)
                .OrderBy(pr => pr.Tarefa);

                ViewData["ProFK"] = new SelectList(profissao, "Id", "Tarefa");
                return View(pessoa);
            }
            // var auxiliar
            string caminhoCompleto = "";

           
            if (imagem == null)
            {
               // não há ficheiro
               // adicionar msg de erro
                ModelState.AddModelError("", "Adicione uma fotografia, por favor");
                // devolver o controlo à View
                var profissao = (from pr in _context.Profissao
                                 join p in _context.Pessoa on pr.Id equals p.ProfissaoFK
                                 select pr)
                 .OrderBy(pr => pr.Tarefa);

                ViewData["ProFK"] = new SelectList(profissao, "Id", "Tarefa");

                return View(pessoa);
                //pessoa.Foto = "noimage.png";
            }
            else
            {
                // há ficheiro. Mas, será um ficheiro válido?
                if (imagem.ContentType == "image/jpeg" || imagem.ContentType == "image/png" || imagem.ContentType == "image/jpg")
                {
                    // definir o novo nome da fotografia     
                    Guid g;
                    g = Guid.NewGuid();
                    caminhoCompleto = g.ToString(); // determinar a extensão do nome da imagem

                    string extensao = Path.GetExtension(imagem.FileName).ToLower();
                    // caminho completo do ficheiro
                    caminhoCompleto = caminhoCompleto + extensao;

                    // associar este ficheiro aos dados ds foto
                    pessoa.Foto = caminhoCompleto;

                    // localização do armazenamento da imagem
                    string localizacaoFicheiro = _caminho.WebRootPath;
                    caminhoCompleto = Path.Combine(localizacaoFicheiro, "Imagens", caminhoCompleto);
                }
                else
                {
                    // ficheiro não é válido
                    // adicionar msg de erro
                    ModelState.AddModelError("", "Só pode escolher uma imagem");
                    // devolver o controlo à View
                    var profissao = (from pr in _context.Profissao
                                     join p in _context.Pessoa on pr.Id equals p.ProfissaoFK
                                     select pr)
                     .OrderBy(pr => pr.Tarefa);

                    ViewData["ProFK"] = new SelectList(profissao, "Id", "Tarefa");
                    return View(pessoa);
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(pessoa);
                    await _context.SaveChangesAsync();

                    // vou guardar, agora, no disco rígido do Servidor a imagem
                    using var stream = new FileStream(caminhoCompleto, FileMode.Create);
                    await imagem.CopyToAsync(stream);
                    return RedirectToAction(nameof(Index));
                }   
                catch (Exception)
                {
                    ModelState.AddModelError("", "Ocorreu um erro...");

                }
        }
            ViewData["ProFK"] = new SelectList(_context.Profissao.OrderBy(pr => pr.Tarefa), "Id", "Tarefa", pessoa.ProfissaoFK);

            return View(pessoa);
        }

        /// <summary>
        /// mostra a página do edit
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Pessoas/Edit/5
        [Authorize(Roles = "Funcionario,Gestor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var pessoa = await _context.Pessoa.FindAsync(id);
            if (pessoa == null)
            {
                return NotFound();
            }
            ViewData["ProFK"] = new SelectList(_context.Profissao.OrderBy(pr => pr.Tarefa), "Id", "Tarefa", pessoa.ProfissaoFK);

            // guardar o ID do objeto enviado para o browser
            // através de uma variável de sessão
            HttpContext.Session.SetString("NumFotoEmEdicao", pessoa.Foto);
            return View(pessoa);
        }

        // POST: Pessoas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Funcionario,Gestor")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Foto,DataNasc,DataObi,DataInic,Nacionalidade,ProfissaoFK")] Pessoa pessoa,IFormFile imagem)
        {
            if (id != pessoa.Id)
            {
                return NotFound();
            }

            // recuperar o ID do objeto enviado para o browser
            var numIdFoto = HttpContext.Session.GetString("NumFotoEmEdicao");

            

            // var auxiliar
            string caminhoCompleto = "";
            

            if (ModelState.IsValid)
            {
                try
                {
                    if (imagem == null)
                    {
                        pessoa.Foto = numIdFoto;
                    }
                    else
                    {
                        // há ficheiro. Mas, será um ficheiro válido?
                        if (imagem.ContentType == "image/jpeg" || imagem.ContentType == "image/png" || imagem.ContentType == "image/jpg")
                        {
                            // definir o novo nome da fotografia     
                            Guid g;
                            g = Guid.NewGuid();

                            //apagar a imagem anterior

Views/Pessoas/Create.cshtml
@model Watch_List.Models.Pessoa

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input type="file" name="imagem" accept=".jpg,.jpeg,.png" style="color:blue;" />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNasc" class="control-label"></label>
                <input asp-for="DataNasc" class="form-control" />
                <span asp-validation-for="DataNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataObi" class="control-label"></label>
                <input asp-for="DataObi" class="form-control" />
                <span asp-validation-for="DataObi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataInic" class="control-label"></label>
                <input asp-for="DataInic" class="form-control" />
                <span asp-validation-for="DataInic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nacionalidade" class="control-label"></label>
                <input asp-for="Nacionalidade" class="form-control" />
                <span asp-validation-for="Nacionalidade" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="ProfissaoFK" class="control-label"></label>
                <select asp-for="ProfissaoFK" class="form-control" asp-items="ViewBag.ProFK">
                    <option value="0">Escolha uma Profissão, por favor.</option>
                </select>
            </div>


            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à página anterior</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pessoas/Delete.cshtml
@model Watch_List.Models.Pessoa

@{
    ViewData["Title"] = "Apagar";
}

<h1>@ViewData["Title"]</h1>

<h3>Têm a certeza que pretende apagar isto?</h3>
<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Foto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNasc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNasc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataObi)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataObi)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataInic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataInic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nacionalidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nacionalidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfissaoFK)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfissaoFK)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar à página anterior</a>
    </form>
</div>

Views/Pessoas/Details.cshtml
@model Watch_List.Models.Pessoa

@{
    ViewData["Title"] = "Detalhes";
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4>@Html.DisplayFor(model => model.Nome)</h4>
    <hr />
    <dl class="row">
        
        <dd class="col-sm-10">
            <img src="~/Imagens/@Html.DisplayFor(modelItem => modelItem.Foto)"
                 width="500"
                 alt="@Html.DisplayFor(modelItem => modelItem.Nome)"
                 title="@Html.DisplayFor(modelItem => modelItem.Nome)" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataNasc)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataNasc)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataObi)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataObi)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataInic)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataInic)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nacionalidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nacionalidade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProfissaoFK)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProfissaoFK)
        </dd>


        <dt class="col-sm-10">   <br /> </dt>
        @if (Model.ListaDeFilmes.Count == 0) { }
        else
        {

            @foreach (var fil in Model.ListaDeFilmes)
            {
                <dt class="col-sm-10" style="text-align:center">
                    <img src="~/Imagens/@fil.Filme.Poster" title="@fil.Filme.Titulo" height="50" />
                    <br />
                    @fil.Filme.Titulo

                </dt>
            }

        }
    </dl>

</div>
<div>
    @if (User.IsInRole("Gestor") || User.IsInRole("Funcionario"))
    {
        <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
    }
    <a asp-action="Index">Voltar à página anterior</a>
    
</div>

Views/Pessoas/Edit.cshtml
@model Watch_List.Models.Pessoa

@{
    ViewData["Title"] = "Editar";
}

<h1>@ViewData["Title"]</h1>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input type="file" name="imagem" accept=".jpg,.jpeg,.png" style="color:blue;" />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNasc" class="control-label"></label>
                <input asp-for="DataNasc" class="form-control" />
                <span asp-validation-for="DataNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataObi" class="control-label"></label>
                <input asp-for="DataObi" class="form-control" />
                <span asp-validation-for="DataObi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataInic" class="control-label"></label>
                <input asp-for="DataInic" class="form-control" />
                <span asp-validation-for="DataInic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nacionalidade" class="control-label"></label>
                <input asp-for="Nacionalidade" class="form-control" />
                <span asp-validation-for="Nacionalidade" class="text-danger"></span>
            </div>
            

            <div class="form-group">
                <label asp-for="ProfissaoFK" class="control-label"></label>
                <select asp-for="ProfissaoFK" class="form-control" asp-items="ViewBag.ProFK">
                    <option value="0">Escolha uma profissão, por favor.</option>
                </select>
            </div>

            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à página anterior</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pessoas/Index.cshtml
@model IEnumerable<Watch_List.Models.Pessoa>

@{
    ViewData["Title"] = "Pessoas";
}

<h1>@ViewData["Title"]</h1>

@if (User.IsInRole("Gestor") || User.IsInRole("Funcionario"))
{
    <p>
        <a asp-action="Create">Criar Novo</a>
    </p>
    <p>
        <a  asp-area="" asp-controller="PessoaFilmes" asp-action="Index">Adicionar a um filme</a>
    </p>
}
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                
                <th>
                    @Html.DisplayNameFor(model => model.DataNasc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DataObi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DataInic)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nacionalidade)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                <tr>
                    
                    <td>
                        <img src="~/Imagens/@Html.DisplayFor(modelItem => item.Foto)"
                             width="50"
                             alt="@Html.DisplayFor(modelItem => item.Nome)"
                             title="@Html.DisplayFor(modelItem => item.Nome)" />
                        <br />
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    @if (item.DataNasc.Equals(null))
                    {


                        <td>
                            -
                        </td>
                    }
                    else
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.DataNasc)
                        </td>
                    }

                    @if (item.DataObi.Equals(null))
                    {
                        <td>
                            -
                        </td>
                    }
                    else
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.DataObi)
                        </td>
                    }
                    @if (item.DataInic.Equals(null))
                    {
                        <td>
                            -
                        </td>
                    }
                    else
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.DataInic)
                        </td>
                    }

                    <td>
                        @Html.DisplayFor(modelItem => item.Nacionalidade)
                    </td>
                    <td>
                        @if (User.IsInRole("Gestor") || User.IsInRole("Funcionario"))
                        {
                            <a asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                            <a asp-action="Delete" asp-route-id="@item.Id"> Apagar </a>
                        }

                        <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a>

                    </td>
                </tr>
            }
        </tbody>
    </table>