Controllers/FilmesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Watch_List.Data;
using Watch_List.Models;

namespace Watch_List.Controllers
{
    [Authorize]
    public class FilmesController : Controller
    {
        /// <summary>
        /// Representa a bd
        /// </summary>
        private readonly WatchListDbContext _context;

        /// <summary>
        /// este atributo contém os dados da app web no servidor
        /// </summary>
        private readonly IWebHostEnvironment _caminho;

        /// <summary>
        /// Recolhe os dados da pessoa que se autenticou
        /// </summary>
        private readonly UserManager<ApplicationUser> _userManager;

        public FilmesController(WatchListDbContext context, IWebHostEnvironment caminho,UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _caminho = caminho;
            _userManager = userManager;

        }

        /// <summary>
        /// Mostra uma lista de filmes
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        // GET: Filmes
        public async Task<IActionResult> Index()
        {

            
            // return View(filmes);
            return View(await _context.Filme.ToListAsync());
        }

        /// <summary>
        /// Mostra os detalhes de um filme
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Filmes/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var filme = await _context.Filme
                .FirstOrDefaultAsync(m => m.Id == id);

            ViewData["ListaDePessoas"] = await (from f in _context.Filme
                                                join pf in _context.PessoaFilme on f.Id equals pf.FilmeFK
                                                join p in _context.Pessoa on pf.PessoaFK equals p.Id
                                                where f.Id == id
                                                select p).ToListAsync();

            ViewData["ListaDeGeneros"] = await (from f in _context.Filme
                                                join gf in _context.FilmeGenero on f.Id equals gf.FilmeFK
                                                join g in _context.Genero on gf.GeneroFK equals g.Id
                                                where f.Id == id
                                                select g).ToListAsync();

            if (filme == null)
            {
                return RedirectToAction("Index");
            }

            return View(filme);
        }

        // GET: Filmes/Create
        [Authorize(Roles = "Funcionario,Gestor")]
        public IActionResult Create()
        {
            

            return View();
        }

        // POST: Filmes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Funcionario,Gestor")]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Ano,Resumo,Poster,Trailer")] Filme filme, IFormFile foto)
        {
            

            string caminhoCompleto = "";
            bool haImagem = false;

            // avaliar se  o utilizador escolheu uma opção válida na dropdown
            /******************************************/


            if (foto == null)
            {
                // não há ficheiro!
                
                filme.Poster = "noimage.png";
            }
            else
            {
                // há ficheiro.
                
                if (foto.ContentType == "image/jpeg" || foto.ContentType == "image/png" )
                {
                    //existe imagem

                    Guid g;
                    g = Guid.NewGuid();
                    // identificar a Extensão do ficheiro
                    string extensao = Path.GetExtension(foto.FileName).ToLower();
                    // nome do ficheiro
                    string nome = g.ToString() + extensao;
                    

                    // Identificar o caminho onde o ficheiro vai ser guardado
                    caminhoCompleto = Path.Combine(_caminho.WebRootPath, "Imagens",nome);
                    // associar o nome da fotografia 
                    filme.Poster = nome;
                    // assinalar que existe imagem
                    haImagem = true;
                }
                else
                {

                    filme.Poster = "noimage.png";
                }
               

            }
            if (ModelState.IsValid)
            {
                try { 
                    _context.Add(filme);
                    await _context.SaveChangesAsync();
               
                    if (haImagem)
                    {
                        using var stream = new FileStream(caminhoCompleto, FileMode.Create);
                        await foto.CopyToAsync(stream);
                    }

                    // redireciona o utilizador para a View Index
                    return RedirectToAction(nameof(Index));
                    }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Ocorreu um erro...");

                }

            }
           
            ViewData["ListFilmes"] = new SelectList(_context.Filme.OrderBy(c => c.Titulo), "Id", "Titulo", foto);

            return View(filme);
            
        }

        // GET: Filmes/Edit/5
        [Authorize(Roles = "Funcionario,Gestor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme.FindAsync(id);
            if (filme == null)
            {
                return NotFound();
            }

            ViewData["ListFilmes"] = new SelectList(_context.Filme.OrderBy(c => c.Titulo), "Id", "Titulo", filme.Poster);

            // guardar o ID do objeto enviado para o browser
            // através de uma variável de sessão
            HttpContext.Session.SetInt32("NumFotoEmEdicao", filme.Id);

            return View(filme);
        }

        // POST: Filmes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Funcionario,Gestor")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Ano,Resumo,Poster,Trailer")] Filme filme,IFormFile imagem)
        {
            if (id != filme.Id)
            {
                return NotFound();
            }

            // recuperar o ID do objeto enviado para o browser
            var numIdFoto = HttpContext.Session.GetString("NumFotoEmEdicao");



            // var auxiliar
            string caminhoCompleto = "";


            if (ModelState.IsValid)
            {
                try
                {
                    if (imagem == null)
                    {
                        filme.Poster = numIdFoto;
                    }
                    else
                    {
                        // há ficheiro. Mas, será um ficheiro válido?
                        if (imagem.ContentType == "image/jpeg" || imagem.ContentType == "image/png" || imagem.ContentType == "image/jpg")
                        {
                            // definir o novo nome da fotografia     
                            Guid g;
                            g = Guid.NewGuid();

                            //apagar a imagem anterior
                            string localizacaoFicheiro = _caminho.WebRootPath;
                            caminhoCompleto = Path.Combine(localizacaoFicheiro, "Imagens", numIdFoto);
                            if (System.IO.File.Exists(caminhoCompleto))
                            {
                                System.IO.File.Delete(caminhoCompleto);
                            }

                            caminhoCompleto = g.ToString(); // determinar a extensão do nome da imagem

                            string extensao = Path.GetExtension(imagem.FileName).ToLower();
                            // caminho completo do ficheiro
                            caminhoCompleto = caminhoCompleto + extensao;

                            // associar este ficheiro aos dados ds foto
                            filme.Poster = caminhoCompleto;

                            // localização do armazenamento da imagem

                            caminhoCompleto = Path.Combine(localizacaoFicheiro, "Imagens", caminhoCompleto);
                        }
                        else
                        {
                            // ficheiro não é válido
                            // adicionar msg de erro
                            ModelState.AddModelError("", "Só pode escolher uma imagem");
                            // devolver o controlo à View

                            var profissao = (from pr in _context.Profissao
                                             join p in _context.Pessoa on pr.Id equals p.ProfissaoFK
                                             select pr)
                             .OrderBy(pr => pr.Tarefa);

Controllers/UtilFilmesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Watch_List.Data;
using Watch_List.Models;

namespace Watch_List.Controllers
{

    [Authorize]
    public class UtilFilmesController : Controller
    {
        private readonly WatchListDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public UtilFilmesController(WatchListDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: UtilFilmes
       
        public async Task<IActionResult> Index()
        {
            // var. auxiliar
            string idDaPessoaAutenticada = _userManager.GetUserId(User);




            //Filmes assosciados a um utilizador
            var filmes = await (from f in _context.Filme
                                join uf in _context.UtilFilme on f.Id equals uf.FilFK
                                where uf.UtilIdFK == idDaPessoaAutenticada
                                select new UtilizadoresFilmes { 
                                Id = uf.Id,
                                Titulo = f.Titulo,
                                Ano = f.Ano,
                                Poster = f.Poster,
                                Estado = uf.Estado,
                                FilmeFK = f.Id
                                }).ToListAsync();

            
            return View(filmes);
        }

        // GET: UtilFilmes/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    //var utilFilme = await _context.UtilFilme
        //    //    .Include(u => u.Filme);
                

        //    var filme = await _context.Filme
        //        .FirstOrDefaultAsync(m => m.Id == id);

        //    if (filme == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(filme);
        //}

        // GET: UtilFilmes/Create
        public async Task<IActionResult> Create()
        {
            // Lista de filmes do utilizador autenticado
            //var filmes = await (from f in _context.Filme
            //              join uf in _context.UtilFilme on f.Id equals uf.FilFK
            //              //where uf.UtilIdFK == _userManager.GetUserId(User)
            //              select f).OrderBy(f => f.Titulo).ToListAsync();

            var filmes = await _context.Filme.OrderBy(f => f.Titulo).ToListAsync();

            ViewData["ListaFilmes"] = new SelectList(filmes, "Id", "Titulo");
           
            return View();
        }

        // POST: UtilFilmes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Estado,UtilIdFK,FilFK")] UtilFilme utilFilme)
        {

            utilFilme.UtilIdFK = _userManager.GetUserId(User);


            if (ModelState.IsValid)
            {
                _context.Add(utilFilme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FilFK"] = new SelectList(_context.Filme, "Id", "Titulo", utilFilme.FilFK);
            return View(utilFilme);
        }

        // GET: UtilFilmes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var utilFilme = await _context.UtilFilme.FindAsync(id);
            if (utilFilme == null)
            {
                return NotFound();
            }


            var filmes = await _context.Filme.OrderBy(f => f.Titulo).ToListAsync();

            ViewData["ListaFilmes"] = new SelectList(filmes, "Id", "Titulo");

            return View(utilFilme);
        }

        // POST: UtilFilmes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Estado,UtilIdFK,FilFK")] UtilFilme utilFilme)
        {
            utilFilme.UtilIdFK = _userManager.GetUserId(User);

            if (id != utilFilme.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   
                   

                   utilFilme.Filme = await _context.Filme.FirstAsync(f => f.Id == utilFilme.FilFK);
                    _context.UtilFilme.Update(utilFilme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException )
                {

                    if (!UtilFilmeExists(utilFilme.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var filmes = await _context.Filme.OrderBy(f => f.Titulo).ToListAsync();

            ViewData["ListaFilmes"] = new SelectList(filmes, "Id", "Titulo");
            return View(utilFilme);
        }

        // GET: UtilFilmes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var utilFilme = await _context.UtilFilme
                .Include(u => u.Filme)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (utilFilme == null)
            {
                return NotFound();
            }

            return View(utilFilme);
        }

        // POST: UtilFilmes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var utilFilme = await _context.UtilFilme.FindAsync(id);
            _context.UtilFilme.Remove(utilFilme);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UtilFilmeExists(int id)
        {
            return _context.UtilFilme.Any(e => e.Id == id);
        }
    }
}

Views/UtilFilmes/Create.cshtml
@model Watch_List.Models.UtilFilme

@{
    ViewData["Title"] = "Criar";
}

<h1>@ViewData["Title"]</h1>

<h4>Filmes dos utilizadores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="UtilIdFK" class="control-label"></label>
                <input asp-for="UtilIdFK" class="form-control" />
                <span asp-validation-for="UtilIdFK" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="FilFK" class="control-label"></label>
                <select asp-for="FilFK" class ="form-control" asp-items="ViewBag.ListaFilmes"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
   <a asp-action="Index">Voltar à página anterior</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/UtilFilmes/Delete.cshtml
@model Watch_List.Models.UtilFilme

@{
    ViewData["Title"] = "Apagar";
}

<h1>@ViewData["Title"]</h1>

<h3>Têm a certeza que pretende apagar isto?</h3>
<div>
    <h4>Filmes dos utilizadores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UtilIdFK)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UtilIdFK)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Filme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Filme.Titulo)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
       <a asp-action="Index">Voltar à página anterior</a>
    </form>
</div>

Views/UtilFilmes/Details.cshtml
@model Watch_List.Models.UtilFilme

@{
    ViewData["Title"] = "Detalhes";
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4>Filmes dos utilizadores</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UtilIdFK)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UtilIdFK)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Filme)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Filme.Titulo)
        </dd>
    </dl>
</div>
<div>
    
        <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
    
    <a asp-action="Index">Voltar à página anterior</a>
</div>

Views/UtilFilmes/Edit.cshtml
@model Watch_List.Models.UtilFilme

@{
    ViewData["Title"] = "Editar";
}

<h1>@ViewData["Title"]</h1>

<h4>Filmes dos utilizadores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="UtilIdFK" class="control-label"></label>
                <input asp-for="UtilIdFK" class="form-control" />
                <span asp-validation-for="UtilIdFK" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="FilFK" class="control-label"></label>
                <select asp-for="FilFK" class="form-control" asp-items="ViewBag.ListaFilmes"></select>
                <span asp-validation-for="FilFK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
   <a asp-action="Index">Voltar à página anterior</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/UtilFilmes/Index.cshtml
@model IEnumerable<Watch_List.Models.UtilizadoresFilmes>

 @{
    ViewData["Title"]="Filmes do Utilizador" ;
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create">Criar Novo</a>
</p>


<table class="table">
    <thead>
        
        <tr>
           
                <th>
                    @Html.DisplayNameFor(model => model.Titulo)
                </th>
            
            <th>

                @Html.DisplayNameFor(model => model.Ano)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
           

        <td>
            <img src="~/Imagens/@Html.DisplayFor(modelItem => item.Poster)"
                 width="50"
                 alt="@Html.DisplayFor(modelItem => item.Titulo)"
                 title="@Html.DisplayFor(modelItem => item.Titulo)" />
            <br />
            @Html.DisplayFor(modelItem => item.Titulo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ano)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>


            <a asp-action="Edit" asp-route-id="@item.Id">Editar</a>
            <a asp-action="Delete" asp-route-id="@item.Id"> Apagar </a>

            <a  asp-controller="Filmes" asp-action="Details" asp-route-id="@item.FilmeFK">Detalhes</a>
        </td>
        </tr>
        }
    </tbody>
</table>

Views/UtilFilmes/Index2.cshtml
@model IEnumerable<Watch_List.Models.UtilFilme>

 @{
    ViewData["Title"]="Filmes do Utilizador" ;
}

<h1>@ViewData["Title"]</h1>
@if (User.IsInRole("Gestor") || User.IsInRole("Funcionario"))
{
<p>
    <a asp-action="Create">Criar Novo</a>
</p>
}

<table class="table">
    <thead>
        
        <tr>
            @if (User.IsInRole("Gestor"))
            {
                <th>
                    @Html.DisplayNameFor(model => model.UtilIdFK)
                </th>
            }
            <th>

                @Html.DisplayNameFor(model => model.Filme)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            @if (User.IsInRole("Gestor"))
            {
                <td>
                    @Html.DisplayFor(modelItem => item.UtilIdFK)
                </td>
            }

        <td>
            <img src="~/Imagens/@Html.DisplayFor(modelItem => item.Filme.Poster)"
                 width="50"
                 alt="@Html.DisplayFor(modelItem => item.Filme.Poster)"
                 title="@Html.DisplayFor(modelItem => item.Filme.Poster)" />
            <br />
            @Html.DisplayFor(modelItem => item.Filme.Titulo)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>*@
        <td>


            <a asp-action="Edit" asp-route-id="@item.Id">Editar</a>
            <a asp-action="Delete" asp-route-id="@item.Id"> Apagar </a>

            <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
        </td>
        </tr>
        }
    </tbody>
</table>